### ISSUE TITLE
Elm package installer typos

### ISSUE THREAD

**Issue by knewter** [eeue56/json-to-elm#15]
`elm-package install -- yes noredink/elm-decode-pipeline` is what's in there right now. There's an extra space before yes, and NRI needs to have proper capitalization. Just wanted to report it!

**Comment by osmestad** [comment]
I still see this at: http://noredink.github.io/json-to-elm/ (when selecting pipeline decoder)
 elm-package install -- yes noredink/elm-decode-pipeline
Is that generated from this repo? (looks like it is fixed here)
Searching GitHub I only found it one other place:
https://github.com/eeue56/elm-to-elixir/blob/master/src/TypeAlias.elm#L667

**Comment by eeue56** [comment]
Yeah, I just haven't regenerated it since. Will do so soon
