### ISSUE TITLE
Camel-case-ize properties with spaces

### ISSUE THREAD

**Issue by tmcw** [eeue56/json-to-elm#18]
An input of

``` js
{ "hi there": true }
```

Produces a record type of

``` elm
type alias Something =
    { hi there : Bool
    }
```

Which is invalid Elm syntax - what will actually be generated is

``` elm
type alias Something =
    { hiThere : Bool
    }
```

Happy to contribute a PR, but currently stuck on [elm 0.17 compatibility - this package is currently for 0.16.x](https://github.com/eeue56/json-to-elm/blob/master/elm-package.json#L7). Updating to 0.17 in that line of elm-package.json produces a generic

```
Error: Unable to find a set of packages that will work with your constraints.
```

So I'm not sure what would be necessary to make the packages fit the constraints.

**Comment by tmcw** [comment]
Closing; no response.

**Comment by eeue56** [comment]
@tmcw Make a PR against the 0.16 code base

**Comment by eeue56** [comment]
This would be the place to get started -> https://github.com/eeue56/json-to-elm/blob/master/elm/TypeAlias.elm#L50
