### ISSUE TITLE
Top-level alias and extra aliases may override one another

### ISSUE THREAD

**Issue by ento** [eeue56/json-to-elm#2]
For both Elm and Python version. This might not happen often (or at all) in practice, but it puzzled me a bit when playing with the [online demo](http://noredink.github.io/json-to-elm/).
- Elm:
  - toplevel alias name: Foo
  - json: `{"foo": {"foo": {"foo": "deeply nested"}}}`

```
type alias Foo =
    { foo : Foo
    }

type alias Foo =
    { foo : Foo
    }

type alias Foo =
    { foo : String
    }
```
- Python: generating from a `foo.json` with content `{"foo": {"foo": {"foo": "deeply nested"}}}` gives:

```
type alias Foo =
    { foo : String
    }


type alias Foo =
    { foo : Foo
    }


type alias Foo =
    { foo : Foo
    }
```
- Note the fact in readme
- or raise if there is a type alias with the same name but with a different definition
- or rename automatically

**Comment by eeue56** [comment]
Technically, you aren't allowed recursive type aliases in Elm. I think the nicest path is to rename automatically, but with a warning that the json data is complex. What do you think @ento? Also thanks for trying it out!

**Comment by ento** [comment]
I'm swaying between bailing out and renaming:
- Using the same property name for different kinds of things seems like a bad design: a tool should keep users from shooting themselves in the foot
  - -> raise
  - But also: a type alias with a field named after the alias name _might_ make sense in some cases `Book = { book : ... }`  (can't think of a compelling one though)
- And also: I've felt frustration with tools that are overly restrictive in the past
  - -> rename

Sooo, I agree the nicest middle ground is to rename automatically with a warning.

**Comment by eeue56** [comment]
This was quite hard to fix, but I fixed it for the Elm version. Will think about what to do in the Python version, since I expect there's a nicer way of doing it
