### ISSUE TITLE
Broken by Grammerly plugin for chrome

### ISSUE THREAD

**Issue by justgage** [eeue56/json-to-elm#22]
While this is totally not your fault, I have Grammarly installed and it really messes up the website. I'm not sure if there's a lot you could do to fix that. I'll at least leave it here for posterity's sake.

**Comment by eeue56** [comment]
Can you define "broken"?

**Comment by justgage** [comment]
Basically it seems like it's getting confused and making the left text box the right text box:

![broken-json-to-elm](https://cloud.githubusercontent.com/assets/164033/22843228/bcf79610-ef95-11e6-8e4b-7a1e80bab6c4.gif)

**Comment by eeue56** [comment]
Yeah, that's users-extensions-at-fault. there's nothing weird my page is doing, so that's a grammerly problem. Going to close this issue. Thanks for reporting anyway!

**Comment by justgage** [comment]
No problem, I thought that it would be nice just in case anyone ran into the same thing.
