### ISSUE TITLE
Deploy on Github Pages

### ISSUE THREAD

**Issue by nikgraf** [eeue56/json-to-elm#8]
Super useful tool :+1: Would be nice if the latest version is always accessible online.

**Comment by eeue56** [comment]
http://noredink.github.io/json-to-elm
 but not yet announced so don't share!

**Comment by nikgraf** [comment]
oh cool, thx

**Comment by eeue56** [comment]
It's also not the latest version, since I'm currently rewriting bits to include self-testing. I expect probably this weekend I'll be able to get a publishable version up
